base:
  ro-bind:
    - /bin
    - /lib
    - /lib64
    - /usr/bin
    - /usr/lib
    - /usr/local/bin
    - /usr/local/lib
    - /usr/share/terminfo
    - /usr/share/ca-certificates
    - /usr/share/zoneinfo

etc:
  ro-bind:
    - /etc/nsswitch.conf
    - /etc/ssl/openssl.cnf
    - /etc/alternatives
    - /etc/passwd
    - /etc/group
    - /etc/resolv.conf
    - /etc/profile.d
    - /etc/bash_completion.d
    - /etc/ssl/certs
    - /etc/ca-certificates
    - /etc/ld.so.cache
    - /etc/ld.so.conf
    - /etc/ld.so.conf.d
    - /etc/localtime

# Default sandbox profile. Override or extend it in ~/.config/acpp/bbwrap.yaml.
sandbox:
  extend:
    - base
    - etc

ssh:
  ro-bind:
    - .ssh
  bind:
    - /run/user/1000/gcr/ssh
  env:
    SSH_AUTH_SOCK: /run/user/1000/gcr/ssh

systemd:
  ro-bind:
    - /run/dbus
    - /sys
  bind:
    - /run/user/1000

docker:
  bind:
    - /var/lib/docker
    - /var/run/docker.sock
