base:
  ro-bind:
    - /bin
    - /lib
    - /lib64
    - /usr/bin
    - /usr/lib
    - /usr/local/bin
    - /usr/local/lib
    - /usr/share/terminfo
    - /usr/share/ca-certificates
    - /usr/share/zoneinfo

etc:
  ro-bind:    
    - /etc/nsswitch.conf
    - /etc/ssl/openssl.cnf  
    - /etc/alternatives
    - /etc/passwd
    - /etc/group
    - /etc/resolv.conf
    - /etc/profile.d
    - /etc/bash_completion.d
    - /etc/ssl/certs
    - /etc/ca-certificates
    - /etc/ld.so.cache
    - /etc/ld.so.conf
    - /etc/ld.so.conf.d
    - /etc/localtime

java:
  ro-bind:
    - /etc/java21-openjdk
    - /etc/java-openjdk

baserepo:
  bind:
    - jr/storj
    - jr/storj2
    - jr/storj3
    - jr/common
    - jr/uplink

docker:
  bind:
    - /var/lib/docker
    - /var/run/docker.sock

psfs:
  ro-bind:
    - .psfs/testdata:testdata
    - .psfs/.netrc:.netrc
    - .psfs/.config/gogcli:.config/gogcli    
    - .psfs/.config/slack-cli:.config/slack-cli

sandbox:
  extend:    
    - base
    - etc
    - java
    - baserepo
    - psfs
  ro-bind:    
    - .cargo/bin
    - dotfiles/.gitignore_global
    - .ssh/code_signing
    - .ssh/known_hosts    
    - .profile
    - .gitconfig
    - .config/gh
    - .config/git
    - .config/uplink
    - .config/worldview
    - .local    
  bind:
    - .npm-global
    - bin
    - go
    - .claude
    - .claude-elek
    - .codex
    - .gemini
    - .cache


ssh:
  ro-bind:
    - .ssh
  bind:
    - /run/user/1000/gcr/ssh
  env:
    SSH_AUTH_SOCK: /run/user/1000/gcr/ssh

systemd:
  ro-bind:
    - /run/dbus
    - /sys
  bind:
    - /run/user/1000
