// Renders the acpp config.yaml a server instance runs with. Mirrors the android
// e2e template approach: each server gets its own XDG_CONFIG_HOME so a
// developer's real ~/.config/acpp is never touched.
import * as path from 'node:path';
import { DB_DSN, AgentSpec } from './env';

// renderConfig builds the config.yaml body for one agent server. `agentDir` is
// the directory holding the agent binary (added to agent_path so the server can
// locate it); `searchDir` is a base directory offered as a project search path.
export function renderConfig(
  agent: AgentSpec,
  agentDir: string,
  searchDir: string,
): string {
  return [
    '# Generated by web/e2e global-setup — do not edit.',
    'database:',
    `  dsn: ${JSON.stringify(DB_DSN)}`,
    `web_addr: ${JSON.stringify(`:${agent.port}`)}`,
    'defaults:',
    `  agent: ${JSON.stringify(agent.command)}`,
    // "none" is required; an empty value defaults to a bwrap sandbox, which the
    // test host may not support.
    '  sandbox: none',
    'agent_path:',
    `  - ${JSON.stringify(agentDir)}`,
    'search_path:',
    `  - ${JSON.stringify(searchDir)}`,
    '',
  ].join('\n');
}

// configPath returns where a given agent's config.yaml lives under its private
// XDG_CONFIG_HOME (configHome).
export function configPath(configHome: string): string {
  return path.join(configHome, 'acpp', 'config.yaml');
}
